### ISSUE TITLE
Bug LoadinFilenotfoundData\World74\leaf01.tg 

### ISSUE THREAD

**Issue by hieuvtd00195** [sven-n/MuMain#28] opened 2024-09-23 16:32 UTC
hello I try run main.exe before build but error , ######LogBe--------------------------------------------Muonline1.03‚(Eng)2024/09/--------------------------------------------<SysteminfOS:Unknown6.CPU:Genu-PenRAM:--------------------------------------------Direct-X:D-------------------------------------------->Toreadco>Enumdispla>Screensize=>Startwindo>OpenGLini----------------------------------------------------------------------------------------<SoundcardiSoundCard:Speakers(HigSoundCardDriver:{0.0.0.00000000}.{fe38567f-a79SoundCard:LGULTRAGEAR(NSoundCardDriver:{0.0.0.00000000}.{7d06a6a8-5af----------------------------------------------------------------------------------------.netruntimFilenotfoundData\Effect\Shiny04.jp>FirstLoadFilenotfoundData\Interface\newui_item_back01.tgFilenotfoundData\Interface\newui_item_back04.tg>LoadinFilenotfoundData\World74\leaf01.tg 
please help

**Comment by hieuvtd00195** [comment] 2024-09-23 17:56
![Screenshot_1](https://github.com/user-attachments/assets/82c6cd10-6a8b-4ca7-8956-f7f3b337381f)

**Comment by sven-n** [comment] 2024-09-24 05:56
I have no idea... the game assets are all checked in the repository.
Your disconnect is caused by something else.

**Closed as completed** 2024-10-17 16:58 UTC
